# Generated by Django 2.2.2 on 2019-06-21 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
