version: '3.7'

volumes:
  moca-db-volume:

services:
  db:
    container_name: 'moca_db'
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_USER: moca_user
      POSTGRES_PASSWORD: moca_password
      POSTGRES_DB: moca_db
    volumes:
      - moca-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    restart: always
    container_name: 'moca_service'
    build: .
    image: moca_service:latest
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      bash -c "
      ./integration/wait-for-it/wait-for-it.sh moca_db:5432 &&
      python apps/manage.py migrate &&
      python apps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "6899:6899"
    depends_on:
      - db
