version: '3.7'

volumes:
  moca-db-volume:
  arch-packages-cache:
  python-libs:

services:
  db:
    container_name: 'moca_db'
    image: mdillon/postgis
    restart: always
    environment:
      - POSTGRES_USER=moca_user
      - POSTGRES_PASSWORD=moca_password
      - POSTGRES_DB=moca_db
    volumes:
      - moca-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    container_name: 'moca_service'
    build: .
    image: moca_service:latest
    command: |
      bash -c "
      xargs -a os_requirements.txt pacman -Syu --needed --cachedir /pacman/cache --force --noconfirm &&
      pip install -qqq -r requirements.txt --exists-action i &&
      python apps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - type: volume
        source: arch-packages-cache
        target: /pacman/cache
        consistency: consistent
      - type: volume
        source: python-libs
        target: /usr/lib/python3.7
        consistency: consistent
    ports:
      - "8000:8000"
    depends_on:
      - db
