version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
    expose:
      - 5432
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:test@db:5432/postgres
    volumes:
      - .:/moca
    ports:
      - "8000:8000"
    depends_on:
      - db
