version: '3.7'

volumes:
  moca-db-volume:

services:
  redis:
    container_name: 'moca_redis_db'
    image: 'redis:5.0-alpine'
    restart: always
    command: redis-server
    volumes:
      - moca-db-volume:/var/lib/redis/data
    expose:
      - 6379 
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery worker -A moca --loglevel=info
    command: |
      bash -c "
      ./integration/wait-for-it/wait-for-it.sh moca_redis_db:6379 &&
      cd apps &&
      celery worker -A moca --loglevel=info"
    volumes:
      - ./:/app
    depends_on:
      - redis
    
  db:
    container_name: 'moca_db'
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_USER: moca_user
      POSTGRES_PASSWORD: moca_password
      POSTGRES_DB: moca_db
    volumes:
      - moca-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    restart: always
    container_name: 'moca_service'
    build: .
    image: moca_service:latest
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      bash -c "
      ./integration/wait-for-it/wait-for-it.sh moca_db:5432 &&
      python apps/manage.py migrate &&
      python apps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "6899:6899"
    depends_on:
      - db
      - celery
