# Generated by Django 2.1.10 on 2019-10-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=15)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moca.Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentmessage',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='appointmentmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediamessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='mediamessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppointmentMessage',
        ),
        migrations.DeleteModel(
            name='MediaMessage',
        ),
    ]
