# Generated by Django 2.1.10 on 2019-11-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
