# Generated by Django 2.1.10 on 2019-12-03 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        ('moca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth_token',
            field=models.ForeignKey(default=datetime.datetime(2019, 12, 3, 0, 29, 30, 474342, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='knox.AuthToken'),
            preserve_default=False,
        ),
    ]
