# Generated by Django 2.1.10 on 2019-10-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('therapist', 'session_type')},
        ),
    ]
