# Generated by Django 2.1.10 on 2019-10-18 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moca.Appointment')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('mediaType', models.CharField(choices=[('PDF', 'pdf'), ('JPEG', 'jpeg')], max_length=6)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attachmentmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='attachmentmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='requestmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responsemessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='responsemessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='responsemessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttachmentMessage',
        ),
        migrations.DeleteModel(
            name='RequestMessage',
        ),
        migrations.DeleteModel(
            name='ResponseMessage',
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
    ]
