# Generated by Django 2.1.10 on 2019-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20191119_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
