# Generated by Django 2.1.10 on 2019-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20191019_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('bank_account', 'Bank'), ('card', 'Card')], max_length=15),
        ),
    ]
