# Generated by Django 2.1.10 on 2019-10-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20191020_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='moca.Message')),
            ],
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='content',
            field=models.TextField(default='HELLO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='moca.Message'),
        ),
    ]
