# Generated by Django 2.1.10 on 2019-10-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20191022_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='moca.Therapist'),
        ),
    ]
