# Generated by Django 2.1.10 on 2019-09-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20190921_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_time_expected', models.DateTimeField()),
                ('end_time_expected', models.DateTimeField()),
                ('is_cancelled', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moca.Address')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moca.Appointment')),
            ],
        ),
    ]
