# Generated by Django 2.1.10 on 2019-09-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0003_appointment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
