# Generated by Django 2.1.10 on 2019-10-21 18:05

from django.db import migrations
import moca.models.user.user


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0003_auto_20191020_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=moca.models.user.user.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
