# Generated by Django 2.1.10 on 2019-08-24 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('moca', '0003_address'),
  ]

  operations = [
    migrations.AlterField(
      model_name='participant',
      name='user',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                              to=settings.AUTH_USER_MODEL),
    ),
  ]
