# Generated by Django 2.1.10 on 2019-11-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0003_therapist_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
