# Generated by Django 2.1.10 on 2019-10-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_auto_20191018_1415'),
        ('moca', '0003_auto_20191019_1830'),
    ]

    operations = [
    ]
