# Generated by Django 2.1.10 on 2019-10-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0004_auto_20191022_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='state',
        ),
    ]
