# Generated by Django 2.1.10 on 2019-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0004_auto_20191115_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
