# Generated by Django 2.1.10 on 2019-09-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0002_therapist_primary_location'),
        ('moca', '0004_auto_20190924_1959'),
    ]

    operations = [
    ]
