# Generated by Django 2.1.10 on 2019-11-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0004_auto_20191119_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompositeMessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messages')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moca.CompositeMessage')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('composite', 'Composite'), ('appointment-request', 'Appointment Request')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ImageMessage',
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
        migrations.AddField(
            model_name='compositemessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='moca.Message'),
        ),
    ]
