# Generated by Django 2.1.10 on 2019-11-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0005_payment_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'high'), ('normal', 'normal'), ('low', 'low')], default='normal', max_length=20)),
                ('description', models.TextField(null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moca.Appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moca.Patient')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moca.Therapist')),
            ],
        ),
    ]
