# Generated by Django 2.1.10 on 2019-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0005_remove_area_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
    ]
