# Generated by Django 2.1.10 on 2019-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0005_merge_20190930_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapist',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
