# Generated by Django 2.1.10 on 2019-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='PENDING', max_length=8),
        ),
    ]
