# Generated by Django 2.1.10 on 2019-11-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0006_auto_20191122_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time_expected',
            new_name='end_time_manual',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time_expected',
            new_name='start_time_manual',
        ),
    ]
