# Generated by Django 2.1.10 on 2019-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0006_unavailablearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='session_type',
            field=models.CharField(choices=[('thirty', 'Thirty minutes'), ('fourtyfive', 'Fourty five minutes'), ('sixty', 'Sixty minutes'), ('evaluation', 'Evaluation')], max_length=20),
        ),
    ]
