# Generated by Django 2.1.10 on 2019-10-24 18:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0007_auto_20191024_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='primary_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
