# Generated by Django 2.1.10 on 2019-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0007_auto_20191001_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
