# Generated by Django 2.1.10 on 2019-10-25 04:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0008_auto_20191024_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='diagnosis'), size=None)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moca.Patient')),
            ],
        ),
    ]
