# Generated by Django 2.1.10 on 2019-10-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0009_auto_20191001_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwayDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='moca.Therapist')),
            ],
        ),
    ]
