# Generated by Django 2.1.10 on 2019-10-12 07:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0009_auto_20191001_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='preferred_ailments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=20),
            preserve_default=False,
        ),
    ]
