# Generated by Django 2.1.10 on 2019-10-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0010_awaydays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaydays',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awaydays', to='moca.Therapist'),
        ),
    ]
