# Generated by Django 2.1.10 on 2019-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0011_therapistcertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistcertification',
            name='image',
            field=models.ImageField(null=True, upload_to='certifications'),
        ),
    ]
