# Generated by Django 2.1.10 on 2019-10-12 13:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0011_auto_20191011_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='tariffs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
