# Generated by Django 2.1.10 on 2019-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0011_auto_20191011_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
