# Generated by Django 2.1.10 on 2019-10-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0012_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='interests',
        ),
    ]
