# Generated by Django 2.1.10 on 2019-10-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0010_therapist_preferred_ailments'),
        ('moca', '0012_therapist_tariffs'),
    ]

    operations = [
    ]
