# Generated by Django 2.1.10 on 2019-10-12 18:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0012_therapist_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='tariffs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
