# Generated by Django 2.1.10 on 2019-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0012_auto_20191025_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='unavailablearea',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.CharField(default='ut', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailablearea',
            name='state',
            field=models.CharField(default='ut', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
