# Generated by Django 2.1.10 on 2019-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0013_remove_therapist_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
