# Generated by Django 2.1.10 on 2019-10-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0013_auto_20191025_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
