# Generated by Django 2.1.10 on 2019-10-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0013_auto_20191013_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentRequestMessage',
            new_name='AppointmentMessage',
        ),
    ]
