# Generated by Django 2.1.10 on 2019-10-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0014_auto_20191025_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='qualifications',
        ),
    ]
