# Generated by Django 2.1.10 on 2019-10-12 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0014_therapist_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='text',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='1618 Beethoven St.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.SmallIntegerField(default=12345),
            preserve_default=False,
        ),
    ]
