# Generated by Django 2.1.10 on 2019-10-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0014_auto_20191013_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediamessage',
            old_name='media',
            new_name='file',
        ),
    ]
