# Generated by Django 2.1.10 on 2019-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0015_auto_20191013_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmessage',
            name='response',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
