# Generated by Django 2.1.10 on 2019-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0015_auto_20191012_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
