# Generated by Django 2.1.10 on 2019-10-30 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0016_auto_20191030_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='moca.Patient'),
            preserve_default=False,
        ),
    ]
