# Generated by Django 2.1.10 on 2019-10-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0016_auto_20191029_0138'),
        ('moca', '0017_review_patient'),
    ]

    operations = [
    ]
