# Generated by Django 2.1.10 on 2019-10-12 16:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0017_auto_20191012_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), size=None)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='moca.Appointment')),
            ],
        ),
    ]
