# Generated by Django 2.1.10 on 2019-10-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0018_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
