# Generated by Django 2.1.10 on 2019-10-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0012_therapist_tariffs'),
        ('moca', '0019_remove_appointment_notes'),
    ]

    operations = [
    ]
