# Generated by Django 2.1.10 on 2019-11-09 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0020_appointmentcancellation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentcancellation',
            name='description',
        ),
    ]
