# Generated by Django 2.1.10 on 2019-10-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0013_merge_20191012_1643'),
        ('moca', '0021_auto_20191012_1805'),
    ]

    operations = [
    ]
