# Generated by Django 2.1.10 on 2019-10-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0014_device'),
        ('moca', '0021_auto_20191012_1805'),
    ]

    operations = [
    ]
