# Generated by Django 2.1.10 on 2019-10-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0022_merge_20191012_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='tariffs',
        ),
        migrations.AddField(
            model_name='price',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='moca.Therapist'),
        ),
    ]
