# Generated by Django 2.1.10 on 2019-11-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0023_auto_20191110_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastviewed',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
