# Generated by Django 2.1.10 on 2019-10-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0023_auto_20191013_1249'),
        ('moca', '0022_merge_20191013_0012'),
    ]

    operations = [
    ]
