# Generated by Django 2.1.10 on 2019-10-14 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0024_merge_20191014_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='preferred_ailments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=20),
        ),
    ]
