# Generated by Django 2.1.10 on 2019-11-12 00:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0026_auto_20191111_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaydays',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='awaydays',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='awaydays',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_days', to='moca.Therapist'),
        ),
        migrations.AlterField(
            model_name='note',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), blank=True, null=True, size=None),
        ),
    ]
