# Generated by Django 2.1.10 on 2019-11-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moca', '0027_auto_20191112_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
    ]
