version: '3.7'

services:
  moca_db:
    image: mdillon/postgis
    restart: always
    environment:
      - POSTGRES_USER=moca_user
      - POSTGRES_PASSWORD=moca_password
      - POSTGRES_DB=moca_db
    expose:
      - 5432
    ports:
      - 5432

  moca_service:
    build:
      context: ..
      dockerfile: integration/Dockerfile
    image: moca_service:latest
    command: |
      bash -c "
      ./integration/wait-for-it.sh moca_db:5432 &&
      python apps/manage.py migrate &&
      python apps/manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 8000
    depends_on:
      - moca_db
