FROM archlinux/base

RUN pacman -Syu --noconfirm python-pip docker npm
RUN pip install tavern pytest-faker

RUN npm install @openapitools/openapi-generator-cli -g
ENV PATH '/usr/bin:$PATH'
RUN pacman -S --noconfirm jdk8-openjdk
